### ISSUE TITLE
使用MySQL数据库时，在菜单根目录下添加项目会出错

### ISSUE THREAD

**Issue by icesunx** [cyq1162/Aries#2]
使用MySQL数据库时，在菜单根目录下添加项目会出错。
在菜单根目录添加项目后，会导致系统无法正常使用。
具体报错为
“System.FormatException”类型的异常在 mscorlib.dll 中发生，但未在用户代码中进行处理
其他信息: 无法识别的 GUID 格式。

原因是新增到sys_menu的条目的ParentMenuID在添加时被设置为空字符。应改为null。

**Comment by cyq1162** [comment]
已修正！
